api_version = "2026-04"

[[extensions]]
name = "t:name"
handle = "visual-bundle-discount"
type = "function"
uid = "80ac8c79-85e9-438d-efc8-c20c3904d9b8443e0683"
description = "t:description"

  [[extensions.targeting]]
  target = "purchase.product-discount.run"
  input_query = "src/run.graphql"
  export = "run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
